[build]
builder = "heroku/buildpacks:22"
buildpacks = ["heroku/java"]

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[environments.production.variables]
ENV = "production"
TZ = "Asia/Ho_Chi_Minh"
MAVEN_OPTS = "-Xmx1024m" 